setup_travis


default_platform(:ios)

platform :ios do

  desc "test"
  lane :test do
    match(type: "appstore")
    build_app(scheme: "AlfameRepresentativeStatusUi",
    export_method: "app-store",
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    create_keychain(
      name: ENV["KEYCHAIN"],
      password: ENV["MYAPP_RELEASE_STORE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    unlock_keychain(
      path: ENV["KEYCHAIN"],
      add_to_search_list: :replace,
      password: ENV['MYAPP_RELEASE_STORE_PASSWORD']
    )
    # increment_build_number(xcodeproj: "AlfameRepresentativeStatusUi.xcodeproj")
    match(
      keychain_name: ENV["KEYCHAIN"],
      keychain_password: ENV["MYAPP_RELEASE_STORE_PASSWORD"],
      type: "adhoc",
      readonly: is_ci
    )
    build_app(scheme: "AlfameRepresentativeStatusUi",
    export_method: "ad-hoc",
    )
    upload_to_testflight(
      distribute_external: false
    )
  end
end
