setup_travis


default_platform(:ios)

platform :ios do

  desc "test"
  lane :test do
    # match(type: "adhoc")
    build_app(scheme: "customerrepresentativestatus",
    export_method: "ad-hoc",
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    create_keychain(
      name: ENV["KEYCHAIN"],
      password: ENV["MYAPP_RELEASE_STORE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    unlock_keychain(
      path: ENV["KEYCHAIN"],
      add_to_search_list: :replace,
      password: ENV['MYAPP_RELEASE_STORE_PASSWORD']
    )
    # increment_build_number(xcodeproj: "customerrepresentativestatus.xcodeproj")
    match(type: "development",
      keychain_name: ENV["KEYCHAIN"],
      keychain_password: ENV["MYAPP_RELEASE_STORE_PASSWORD"],
      type: "appstore",
      readonly: is_ci
    )
    build_app(scheme: "customerrepresentativestatus",
    export_method: "ad-hoc",
    )
    # upload_to_testflight
  end
end
